### ISSUE TITLE
[BUG] - Bamboo specs file bevat een foute plan key

### ISSUE THREAD

**Issue by SanderKleykens** [milieuinfo/webcomponent-vl-blueprint#20]
**Omschrijf het probleem**
De specs file ziet er nu uit als:

```
---
version: 2
plan:
  project-key: WEBCO
  key: VLUIUBLUEPRINT
  name: webcomponent-vl-ui-blueprint
.
.
.
---
version: 2
plan:
  key: VLUIBLUEPRINT

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
```

De onderste plan.key moet eigenlijk "WEBCO-VLUIBLUEPRINT" zijn.

**Gewenst gedrag**
Specs file moet er uit zien als:

```
---
version: 2
plan:
  project-key: WEBCO
  key: VLUIUBLUEPRINT
  name: webcomponent-vl-ui-blueprint
.
.
.
---
version: 2
plan:
  key: WEBCO-VLUIBLUEPRINT

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
```
